### ISSUE TITLE
Main Menu fails to get valid `NetworkManager` in built game

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/ArizonaFrameworkSample#1]
In a built version of the Arizona Framework, the main menu fails to get the network manager. Here's the log information:
```
[ 00:00:04.904 ]: [Warning] WaitForLoaded asset 'FlaxEngine.JsonAsset, 837e13f846891f112631629391002427, [path]/ArizonaFrameworkSample/Output/Windows/Content/Settings/Network Settings.json' failed. No loading task attached and asset is not loaded.
```

**Comment by PrecisionRender** [comment]
Creating a new `NetworkSettings` file and assigning it in `GameSettings` seemed to solve the issue.

**Comment by mafiesto4** [comment]
Correct, the framework uses default Network Manager which utilizes Network Settings. I'll clarify this in docs.
